-- Generated by Sill. Edit `sill.position` / `sill.margin` in
-- ~/.config/ghost/settings.toml instead; Sill rewrites this file.
o.window("^dev\\.ghost\\.sill$", {
  size = { "560", "720" },
  move = { "(monitor_w-560-60)", "46" },
})
