-- Personal window rules.

-- Sill (dev.ghost.sill) — successor to the shelf: screenshots + pinned stash
-- (clipboard in Phase 2). Same xdg_toplevel-faking-an-overlay pattern, same
-- reasons (a layer surface cannot originate a drag; the bar stacks above all
-- toplevels so attachment below y=44 is faked). Fixed 560x720 transparent
-- canvas at the top-right; y = reserved-top (44) + 2. The app cuts a Wayland
-- input region to the visible chip/panel, so the empty canvas stays
-- click-through.
local sill = "^dev\\.ghost\\.sill$"

-- Geometry is regenerated by Sill itself into hypr/sill-position.lua when the
-- `sill.position` setting changes; this file only carries the behaviour rules.
-- A fixed-size canvas is deliberate: the window is set non-resizable, so a
-- size rule is refused by the client and Hyprland then drops the paired move
-- too, leaving the window centred. Learned the hard way.
require("hypr.sill-position")

o.window({ class = sill }, {
  tag = "-default-opacity",
  float = true,
  pin = true,
  no_initial_focus = true,  -- never take focus away from what you were typing in
  no_follow_mouse = true,   -- ...and don't grab it on hover either
  no_anim = true,           -- the app animates its own expand/collapse
  no_dim = true,
  no_blur = true,
  no_shadow = true,
  border_size = 0,
  rounding = 0,             -- the panel draws its own corners in CSS
  opacity = "1 1",
})

-- Ghost Settings TUI: float from all three entry points (keybind, terminal
-- via launch-or-focus, .desktop) -- same app-id everywhere. 1040x720 ~= a
-- 104x34-cell foot window, comfortably above the TUI's 84x24 full layout.
o.window({ class = "^ghost-settings$" }, {
  float = true,
  size = "1040 720",
  center = true,
})
